# Generated by Django 3.2 on 2023-08-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/category/')),
            ],
        ),
    ]
