# Generated by Django 3.2 on 2023-08-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0002_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='featured_video',
        ),
    ]
