# Generated by Django 3.2 on 2023-08-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0003_remove_course_featured_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
