# Generated by Django 3.2 on 2023-08-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0004_alter_course_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_level', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
