# Generated by Django 3.2 on 2023-08-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0005_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
