# Generated by Django 3.2 on 2023-08-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0010_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lms_main.course'),
        ),
    ]
