# Generated by Django 3.2 on 2023-08-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0011_requirement_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_main.course'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_points',
            field=models.CharField(max_length=500),
        ),
    ]
