# Generated by Django 3.2 on 2023-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0012_auto_20230818_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement_points',
            field=models.CharField(default='no requirements', max_length=500),
        ),
    ]
