# Generated by Django 3.2 on 2023-08-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0015_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='time_duration',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
