# Generated by Django 3.2 on 2023-08-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0017_alter_video_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name_of_level',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
