# Generated by Django 3.2 on 2023-08-20 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0018_alter_level_name_of_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms_main.level'),
            preserve_default=False,
        ),
    ]
