# Generated by Django 3.2 on 2023-08-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_enrolledcourses'),
        ('lms_main', '0020_addtocart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addtocart',
            unique_together={('course', 'student')},
        ),
    ]
