# Generated by Django 3.2 on 2023-08-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_enrolledcourses'),
        ('lms_main', '0021_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(default=0, max_length=200)),
                ('course_purchase_price', models.IntegerField(default=0, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_main.order')),
                ('user_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.enrolledcourses')),
            ],
        ),
    ]
