# Generated by Django 3.2 on 2023-08-25 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_enrolledcourses'),
        ('lms_main', '0022_saveforlater'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cart',
        ),
    ]
