# Generated by Django 3.2 on 2023-08-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0022_auto_20230826_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
