# Generated by Django 3.2 on 2023-08-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0025_auto_20230826_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='invoice_no',
            field=models.CharField(default=0, max_length=200, unique=True),
        ),
    ]
