# Generated by Django 3.2 on 2023-08-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0026_alter_orderitems_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='item_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='course',
            field=models.CharField(max_length=200),
        ),
    ]
