# Generated by Django 3.2 on 2023-08-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0027_auto_20230826_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='course_purchase_price',
        ),
    ]
