# Generated by Django 3.2 on 2023-08-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0028_remove_orderitems_course_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_main.course'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitems',
            unique_together={('course', 'order')},
        ),
    ]
