# Generated by Django 3.2 on 2023-08-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0029_auto_20230826_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='invoice_no',
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(default=0, max_length=200, unique=True),
        ),
    ]
