# Generated by Django 3.2 on 2023-08-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0030_auto_20230827_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
