# Generated by Django 3.2 on 2023-08-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0031_alter_order_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default=0, max_length=200, unique=True),
        ),
    ]
