# Generated by Django 3.2 on 2023-08-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0034_auto_20230827_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement_points',
            field=models.CharField(default='', max_length=500),
        ),
    ]
