# Generated by Django 3.2 on 2023-08-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0035_alter_requirement_requirement_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='course/featured_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
