# Generated by Django 3.2 on 2023-09-02 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0036_auto_20230831_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='serial_number',
        ),
    ]
