# Generated by Django 3.2 on 2023-09-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0039_alter_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizoption',
            name='option',
            field=models.CharField(max_length=200),
        ),
    ]
