# Generated by Django 3.2 on 2023-09-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0040_alter_quizoption_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizoption',
            name='is_answer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
