# Generated by Django 3.2 on 2023-09-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0042_auto_20230912_0940'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='SaveForLater',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='SaveForLater',
                ),
            ],
                database_operations=[
                migrations.AlterModelTable(
                    name='SaveForLater',
                    table='student_saveforlater',
                ),
            ],
        )
    ]
