# Generated by Django 3.2 on 2023-09-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0043_delete_saveforlater'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Cart',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Cart',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                 name='Cart',
                table='student_cart',
                ),
            ],
        )
    ]
