# Generated by Django 3.2 on 2023-09-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0044_delete_cart'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='order',
        #     name='student',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='order',
                    name='student',
                ),
            ],
            database_operations=[],
        )
    ]
        