# Generated by Django 3.2 on 2023-09-18 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0045_remove_order_student'),
        ('student', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.order'),
        ),
        # migrations.DeleteModel(
        #     name='Order',
        # ),
        
        migrations.SeparateDatabaseAndState(
             state_operations=[
                 migrations.DeleteModel(
                     name='Order',
                    ),
                ],
                database_operations=[
                 migrations.AlterModelTable(
                     name='Order',
                    table='student_order',
                    ),
                ],
            )
    ]
