# Generated by Django 3.2 on 2023-09-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0046_auto_20230918_0850'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='OrderItems',
        # ),
        
        migrations.SeparateDatabaseAndState(
             state_operations=[
                 migrations.DeleteModel(
                     name='OrderItems',
                    ),
                ],
                        database_operations=[
                 migrations.AlterModelTable(
                     name='OrderItems',
                                        table='student_orderitems',
                    ),
                ],
            )
    ]
