# Generated by Django 3.2 on 2023-09-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        ('lms_main', '0047_delete_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.category'),
        ),
        # migrations.DeleteModel(
        #     name='Category',
        # ),
        
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Category',
                ),
            ],
                    database_operations=[
             migrations.AlterModelTable(
                 name='Category',
                                    table='instructor_category',
                ),
            ],
        )
    ]
