# Generated by Django 3.2 on 2023-09-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_lesson_requirement_whatyouwilllearn'),
        ('user', '0015_alter_playingvideo_lesson'),
        ('lms_main', '0049_auto_20230918_1117'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
             state_operations=[
                 migrations.RemoveField(
                    model_name='requirement',
                    name='course',
                    ),
                ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='whatyouwilllearn',
                    name='course',
                ),
            ]
        ),
        # migrations.AlterField(
        #     model_name='video',
        #     name='lesson',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.lesson'),
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
             migrations.AlterField(
                 model_name='video',
                    name='lesson',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instructor.lesson'),
                ),
            ],
                       # You're reusing an existing table, so do nothing
         database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                 name='Lesson',
                ),
            ],
                    database_operations=[
             migrations.AlterModelTable(
                 name='Lesson',
                                    table='instructor_lesson',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Requirement',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Requirement',
                    table='instructor_requirement',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='WhatYouWillLearn',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='WhatYouWillLearn',
                    table='instructor_whatyouwilllearn',
                ),
            ],
        ),
    ]
