# Generated by Django 3.2 on 2023-09-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_auto_20230918_1359'),
        ('user', '0016_auto_20230918_1359'),
        ('student', '0006_auto_20230918_1359'),
        ('lms_main', '0050_auto_20230918_1133'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='question',
        #     name='course',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='question',
                    name='course',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='instructor.course'),
                ),
            ],
        ),
        # migrations.AlterField(
        #     model_name='video',
        #     name='course',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='video',
                    name='course',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='instructor.course'),
                ),
            ],
        ),
        # migrations.AlterField(
        #     model_name='video',
        #     name='lesson',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.lesson'),
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='video',
                    name='lesson',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='instructor.lesson'),
                ),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Course',
        # ),
        migrations.SeparateDatabaseAndState(
         state_operations=[
             migrations.DeleteModel(
                 name='Course',
                ),
            ],
                database_operations=[
                migrations.AlterModelTable(
                name='Course',
                table='instructor_course',
                ),
            ],
        )
    ]
