# Generated by Django 3.2 on 2023-09-19 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20230919_0150'),
        ('instructor', '0005_auto_20230919_0150'),
        ('lms_main', '0051_auto_20230918_1359'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='question',
        #     name='course',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='question',
                    name='course',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='instructor.course'),
                ),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Video',
        # ),
        migrations.SeparateDatabaseAndState(
         state_operations=[
            migrations.DeleteModel(
                 name='Video',
                ),
            ],
                database_operations=[
                migrations.AlterModelTable(
                name='Video',
                table='instructor_video',
                ),
            ],
        )
    ]
