# Generated by Django 3.2 on 2023-09-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0052_auto_20230919_0150'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='quizoption',
                        name='question_id',
                ),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Question',
        # ),
        migrations.SeparateDatabaseAndState(
             state_operations=[
                migrations.DeleteModel(
                    name='Question',
                    ),
                ],
                database_operations=[
                 migrations.AlterModelTable(
                    name='Question',
                    table='instructor_question',
                    ),
                ],
            ),
        # migrations.DeleteModel(
        #     name='QuizOption',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='QuizOption',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='QuizOption',
                    table='instructor_questionoption',
                ),
            ],
        ),
    ]
