# Generated by Django 3.2 on 2023-09-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Level',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name_of_level', models.CharField(blank=True, default=None, max_length=30, null=True)),
        #     ],
        # ),
        
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Level',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name_of_level', models.CharField(blank=True, default=None, max_length=30, null=True)),
                    ],
                ),
            ],
    
        ),
    ]
