# Generated by Django 3.2 on 2023-09-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_playingvideo_lesson'),
        ('instructor', '0003_lesson_requirement_whatyouwilllearn'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Course',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=300)),
        #         ('description', models.TextField()),
        #         ('created_at', models.DateField(auto_now_add=True)),
        #         ('featured_image', models.ImageField(blank=True, null=True, upload_to='course/featured_images/')),
        #         ('price', models.IntegerField(blank=True, default=0, null=True)),
        #         ('discount', models.IntegerField(blank=True, null=True)),
        #         ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
        #         ('status', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT')], max_length=100, null=True)),
        #         ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.instructor')),
        #         ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.category')),
        #         ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.level')),
        #     ],
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Course',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True,
                                                   primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=300)),
                        ('description', models.TextField()),
                        ('created_at', models.DateField(auto_now_add=True)),
                        ('featured_image', models.ImageField(blank=True,
                                                             null=True, upload_to='course/featured_images/')),
                        ('price', models.IntegerField(
                            blank=True, default=0, null=True)),
                        ('discount', models.IntegerField(blank=True, null=True)),
                        ('slug', models.SlugField(blank=True,
                                                  max_length=300, null=True, unique=True)),
                        ('status', models.CharField(choices=[
                            ('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT')], max_length=100, null=True)),
                        ('author', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE, to='user.instructor')),
                        ('category', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE, to='instructor.category')),
                        ('level', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE, to='instructor.level')),
                    ],
                    ),
                ],
        ),
        # migrations.AlterField(
        #     model_name='lesson',
        #     name='course',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='lesson',
                    name='course',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instructor.course'),
                ),
            ],
        ),
        # migrations.AlterField(
        #     model_name='requirement',
        #     name='course',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='requirement',
                    name='course',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='instructor.course'),
                ),
            ],
        ),
        # migrations.AlterField(
        #     model_name='whatyouwilllearn',
        #     name='course',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='whatyouwilllearn',
                    name='course',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='instructor.course'),
                ),
            ],
        ),
    ]
