import django.db.models.deletion
from django.db import migrations, models


# Generated by Django 3.2 on 2023-09-19 04:16


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_auto_20230919_0150'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Question',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True,
                         primary_key=True, serialize=False, verbose_name='ID')),
                        ('question_text', models.CharField(max_length=300)),
                        ('course', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE, to='instructor.course')),
                    ],
                ),
            ],
        ),
        # migrations.AlterField(
        #     model_name='lesson',
        #     name='course',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='lesson',
                    name='course',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='instructor.course'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='requirement',
                    name='course',
                    field=models.ForeignKey(
                         on_delete=django.db.models.deletion.PROTECT, to='instructor.course'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='whatyouwilllearn',
                    name='course',
                    field=models.ForeignKey(
                         on_delete=django.db.models.deletion.PROTECT, to='instructor.course'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='QuizOption',
                    fields=[
                         ('id', models.BigAutoField(auto_created=True,
                                                    primary_key=True, serialize=False, verbose_name='ID')),
                        ('option', models.CharField(max_length=200)),
                        ('is_answer', models.BooleanField(
                            blank=True, default=False)),
                        ('question_id', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE, to='instructor.question')),
                    ],
                ),
            ],
        ),
    ]
