# Generated by Django 3.2 on 2023-09-19 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_auto_20230919_0416'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='lesson',
        #     name='course',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        # ),
        migrations.SeparateDatabaseAndState(
             state_operations=[
                 migrations.AlterField(
                    model_name='lesson',
                        name='course',
                                        field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instructor.course'),
                    ),
                ],
            ),
        # migrations.AlterField(
        #     model_name='requirement',
        #     name='course',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='requirement',
                    name='course',
                    field=models.ForeignKey(
                         on_delete=django.db.models.deletion.PROTECT, to='instructor.course'),
                ),
            ],
        ),
        # migrations.AlterField(
        #     model_name='whatyouwilllearn',
        #     name='course',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='whatyouwilllearn',
                    name='course',
                    field=models.ForeignKey(
                         on_delete=django.db.models.deletion.PROTECT, to='instructor.course'),
                ),
            ],
        ),
    ]
