# Generated by Django 3.2 on 2023-09-18 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0014_delete_enrolledcourses'),
        ('lms_main', '0042_auto_20230912_0940'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='EnrolledCourses',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_main.course')),
        #         ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
        #     ],
        #     options={
        #         'unique_together': {('course', 'student')},
        #     },
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='EnrolledCourses',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_main.course')),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
                    ],
                    options={
                        'unique_together': {('course', 'student')},
                    },
                ),
            ],
                    # Table already exists. See catalog/migrations/0003_delete_product.py
         database_operations=[],
        ) 
    ]
