# Generated by Django 3.2 on 2023-09-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_delete_enrolledcourses'),
        ('lms_main', '0043_delete_saveforlater'),
        ('student', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='SaveForLater',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('saved_at', models.DateTimeField(auto_now_add=True)),
        #         ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_main.course')),
        #         ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
        #     ],
        #     options={
        #         'unique_together': {('course', 'student')},
        #     },
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SaveForLater',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('saved_at', models.DateTimeField(auto_now_add=True)),
                        ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_main.course')),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
                    ],
                    options={
                        'unique_together': {('course', 'student')},
                    },
                    # database_operations=[],
                )
            ]
        )
    ]
