# Generated by Django 3.2 on 2023-09-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0044_delete_cart'),
        ('user', '0014_delete_enrolledcourses'),
        ('student', '0002_saveforlater'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Cart',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_main.course')),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
                    ],
                    options={
                        'unique_together': {('course', 'student')},
                    },
                ),
        
            ]
        )
    ]
