# Generated by Django 3.2 on 2023-09-18 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_delete_enrolledcourses'),
        ('student', '0003_cart'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Order',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('order_no', models.CharField(default=0, max_length=200, unique=True)),
        #         ('total_price', models.IntegerField(default=0, null=True)),
        #         ('paid_status', models.BooleanField(default=False)),
        #         ('order_date', models.DateTimeField(auto_now_add=True)),
        #         ('pdf_receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
        #         ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
        #     ],
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Order',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order_no', models.CharField(default=0, max_length=200, unique=True)),
                        ('total_price', models.IntegerField(default=0, null=True)),
                        ('paid_status', models.BooleanField(default=False)),
                        ('order_date', models.DateTimeField(auto_now_add=True)),
                        ('pdf_receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
                    ],
                ),
            ],
                    # Table already exists. See catalog/migrations/0003_delete_product.py
         database_operations=[],
        ),
    ]
