# Generated by Django 3.2 on 2023-09-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_course_course_duration'),
        ('user', '0018_delete_playingvideo'),
        ('student', '0008_auto_20230922_1205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playingvideo',
            unique_together={('course', 'student', 'lesson', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='watchedvideo',
            unique_together={('course', 'student', 'lesson', 'video')},
        ),
    ]
