# Generated by Django 3.2 on 2023-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/instructor/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/student/'),
        ),
    ]
