# Generated by Django 3.2 on 2023-08-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230811_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
