# Generated by Django 3.2 on 2023-08-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_about_instructor_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
