# Generated by Django 3.2 on 2023-08-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0033_order_pdf_receipt'),
        ('user', '0010_enrolledcourses'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolledcourses',
            unique_together={('course', 'student')},
        ),
    ]
