# Generated by Django 3.2 on 2023-09-17 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_playingvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='playingvideo',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
