# Generated by Django 3.2 on 2023-09-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_playingvideo_updated_time'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='EnrolledCourses',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='EnrolledCourses',
                    ),
                ],
                database_operations=[
                 migrations.AlterModelTable(
                    name='EnrolledCourses',
                    table='student_enrolledcourses',
                    ),
                ],
            )
    ]
