# Generated by Django 3.2 on 2023-09-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_lesson_requirement_whatyouwilllearn'),
        ('user', '0014_delete_enrolledcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playingvideo',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.lesson'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='playingvideo',
                    name='lesson',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instructor.lesson'),
                ),
            ],
                    # You're reusing an existing table, so do nothing
         database_operations=[],
        )

    ]
