# Generated by Django 3.2 on 2023-09-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20230919_0150'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='PlayingVideo',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='PlayingVideo',
                ),
            ],
                    database_operations=[
                migrations.AlterModelTable(
                    name='PlayingVideo',
                    table='student_playingvideo',
                ),
            ],
        )
    ]
